### ISSUE TITLE
'PROJECT_DIR' is not defined

### ISSUE THREAD

**Issue by GatoAmarilloBicolor** [lukas-blecher/AutoMask#11]
**Describe the bug**

**To Reproduce**
1. Go to ' preferences.'
2. Click on 'install addon.'
3. Scroll down to 'enable it'

 Traceback (most recent call last):
  File "/snap/blender/111/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/fenix/.config/blender/2.92/scripts/addons/automask.py", line 9, in <module>
    PROJECT_DIR
NameError: name 'PROJECT_DIR' is not defined

**Expected behavior**
No want to be enable

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Parameters

**Additional context**

**Comment by lukas-blecher** [comment]
See step 3 in the installation process
> Adding the Project to the Python path: Open automask.py in your favorite text editor and replace PYTHON_PATH with the path to you python site-packages if needed and **PROJECT_DIR with the path to the directory you downloaded this repository to**.

Also see #8 for an example.

**Comment by GatoAmarilloBicolor** [comment]
Oh, now i get this errror.

Traceback (most recent call last):
  File "/snap/blender/111/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/fenix/.config/blender/2.92/scripts/addons/automask.py", line 14, in <module>
    from mask_spline import *
ModuleNotFoundError: No module named 'mask_spline'

Should i install something?

**Comment by lukas-blecher** [comment]
No I think its the same as #10
I don't know why this is happening. 
Can you tell me what version of python you use? and also what Blender version?
Thanks
