### ISSUE TITLE
can't install on linux (ubuntu 19.10)

### ISSUE THREAD

**Issue by j2l** [lukas-blecher/AutoMask#2]
**Describe the bug**
After installing dependencies, there's a missing requirement: imresize and there's no wheel available for Blender's python 3.7m

**To Reproduce**
* Install all dependencies (BTW, skimage is now scikit-image)
* Install AutoMask Blender add-on
  * When trying to enable it throws:
```
Traceback (most recent call last):
  File "/home/pm/Desktop/blender-2.81a-linux-glibc217-x86_64/2.81/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/pm/Desktop/blender-2.81a-linux-glibc217-x86_64/2.81/python/bin/AutoMask-master/automask.py", line 13, in <module>
    from mask_spline import *
  File "/home/pm/Desktop/blender-2.81a-linux-glibc217-x86_64/2.81/python/bin/AutoMask-master/mask_spline.py", line 5, in <module>
    from scipy.misc import imresize
ImportError: cannot import name 'imresize' from 'scipy.misc' (/home/pm/Desktop/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/site-packages/scipy/misc/__init__.py)
```
* Go to 'blender-2.81a-linux-glibc217-x86_64/2.81/python/bin/AutoMask-master'
* ../python3.7m -m pip install imresize --user
  * it throws:
```
ERROR: Could not find a version that satisfies the requirement imresize (from versions: none)
ERROR: No matching distribution found for imresize
```

**Expected behavior**
add-on enabled

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10, Blender 2.81

**Additional context**
Maybe related to https://github.com/scipy/scipy/issues/6212
FTR, I had to copy every packages from `/home/pm/Desktop/blender-2.81a-linux-glibc217-x86_64/2.81/python/lib/python3.7/site-packages` to `/home/pm/.local/lib/python3.7/site-packages` except numpy that was already installed.

**Comment by lukas-blecher** [comment]
Thank you for reporting the issue. I forgot to remove some imports. Could you try again with the updated version?

**Comment by j2l** [comment]
Wow, Thanks Lukas!
It installs, I didn't find a video to test it yet.
BTW, there's still a reference to imresize, not sure if it could fail again in the future:
```
grep -R imresize ./
Binary file ./AutoMask-master/__pycache__/mask_spline.cpython-37.pyc matches

```
Closing this one since it installed.
