### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\Hrijul\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\automask.py", line 248, in execute     proj_dir = paths[-1] IndexError: list index out of range  location: <unknown location>:-1

### ISSUE THREAD

**Issue by hr1jul** [lukas-blecher/AutoMask#5]
**Describe the bug**

**To Reproduce**
1.manually install all packages inside blender not in C user pref
2. pull repo in c user prefs
3. do as told by lukas
4 activate addon
5. load video and track

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/72699438/95681885-e31fa500-0bff-11eb-9955-ca2c8e2b74ae.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Parameters

**Additional context**

**Comment by hr1jul** [comment]
os window 2004

**Comment by lukas-blecher** [comment]
I've actually never tried it with the dependencies installed in blender. So here is what you can do:
In the `automask.py` file, in your case located at `C:\Users\Hrijul\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\automask.py`, line 7 https://github.com/lukas-blecher/AutoMask/blob/18069b712bb5b81f9a38f7e12ba0858726cb392d/automask.py#L7-L10 there is a list defined.

Now find the python executable used in Blender. There locate the directory `site-package` and copy the complete path.
It should look somewhat like this: `C:\Users\user\blender\2.80\python\lib\site-packages`. Paste this path in `automask.py`:
```python
paths = [
    r'C:\Users\user\blender\2.80\python\lib\site-packages'
]
```
Give that a try. Should work.

**Comment by hr1jul** [comment]
Sir,
      That is working but the projec_dir list is broken as it is showing
out of range error

**Comment by hr1jul** [comment]
And I loved your work, only some repackaging is required for easy
installation

**Comment by lukas-blecher** [comment]
Could you elaborate? Is it working? If not, what did you change, what does the path list look like?

**Comment by hr1jul** [comment]
Can we talk.  The  thing is getting inexplicable and confusing.
Ph no 6290818033.
The issue starts with the dependencies
Scikit image installs but skimage refuses to install
Gdal may show hostility
Then it it cok es to python executable and project directory. In which
blender f.. me up with a user pref folder in c and main blender folder. Of
which I fought alot to figure out what to do. As addon will live in add-ons
folder in and the project is pulled in site packages  or add-ons in blender
folder.

After all this.... You have left space in between the list elements python
path and project directory.
Then in automask.py has these list out of range error i  line 248 i guess.

**Comment by lukas-blecher** [comment]
> Scikit image installs but skimage refuses to install

I think those are actually the same modules. I don't think I understand the problem.

How do you want to talk? I'm part of the discord server Blender for science: https://discord.gg/D7yz8x
Catch me there.

**Comment by hr1jul** [comment]
Please only repair automask.py
The list section in broken

**Comment by hr1jul** [comment]
only issue is the in the line 248 249 wrt project dir list

**Comment by hr1jul** [comment]
Python: Traceback (most recent call last):
  File "\automask.py", line 230, in modal
    self._calcs_done = True
  File "\automask.py", line 143, in automask
    crl = [co, rhand, lhand]
  File "C:\Users\Hrijul\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\SiamMask.py", line 21, in track_object
    model = create_model(state)
  File "C:\Users\Hrijul\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\SiamMask.py", line 12, in create_model
    return SiamMask_Tracker(cfg, path)
  File "C:\Users\Hrijul\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\trackers\tracker.py", line 74, in __init__
    model = load_pretrain(model, join(proj_path, 'trackers/SiamMask/model.pth'))
  File "C:\Users\Hrijul\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\trackers\SiamMask\utils\load_helper.py", line 34, in load_pretrain
    pretrained_dict = torch.load(pretrained_path, map_location=device)
  File "F:\all_software\2.90.1\blender-2.91.0-21fec9513969-windows64\2.91\python\lib\site-packages\torch\serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "F:\all_software\2.90.1\blender-2.91.0-21fec9513969-windows64\2.91\python\lib\site-packages\torch\serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "F:\all_software\2.90.1\blender-2.91.0-21fec9513969-windows64\2.91\python\lib\site-packages\torch\serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
OSError: [Errno 22] Invalid argument: 'F:\\all_software\\2.90.1\\blender-2.91.0-21fec9513969-windows64\\2.91\\python\\lib\\site-packages\\, C:\\Users\\Hrijul\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\trackers/SiamMask/model.pth'

location: <unknown location>:-1

**Comment by hr1jul** [comment]
what is this?

**Comment by lukas-blecher** [comment]
can you please show me your `paths` list. That looks like a broken path to me.

**Comment by hr1jul** [comment]
```python
paths = [
r'F:\all_software\2.90.1\blender-2.91.0-21fec9513969-windows64\2.91\python\lib\site-packages,C:\Users\Hrijul\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons'
]
```

**Comment by lukas-blecher** [comment]
We were able to pinpoint the issue on discord. 
The paths were not seperated correctly. 
Closing this issue now
