### ISSUE TITLE
path is not right

### ISSUE THREAD

**Issue by JBetbe** [lukas-blecher/AutoMask#8]
Hi, I found your add-on and I see it so interesting because I'm working with some videos for a kind of Xmas carol and I want to remove some backgrounds. I had problems with final step, I installed all the requirements but I'm not into python,  I can't achieve the right path for python and PROJECT_DIR and I don't know who to do it. It gives me error because the path code isn't well written. Could you show some me example from your installation? I guess it could help.  
Congrats for your job. Thank you for your help.
Cheers!

Joan B.

**Comment by lukas-blecher** [comment]
The setup is quite complicated and can definitely be improved in the future.
Can you show me how you added the path in automask.py#L7-10 
Did you install the dependencies in a separate python? And can you show me the error you get?

**Comment by JBetbe** [comment]
Hi, this is the error in my Blender Info Log
![Captura de Pantalla 2020-12-17 a les 17 50 55](https://user-images.githubusercontent.com/48406431/102517654-98ebf180-4090-11eb-96b2-a55044d1baea.png)

**Comment by lukas-blecher** [comment]
you have to replace `PYTHON_PATH` with your path.
```
paths = [
    '/Users/joan/Library/Python/2.7/lib/site-packages
    '/Users/joan/AutoMask-master'
]
```
Also you need python 3.7 and the path needs to point to the directory `site-packages`.

**Comment by JBetbe** [comment]
ok. thanks.
