### ISSUE TITLE
you have to replace `PYTHON_PATH` with your path.

### ISSUE THREAD

**Issue by JBetbe** [lukas-blecher/AutoMask#9]
you have to replace `PYTHON_PATH` with your path.
```
paths = [
    '/Users/joan/Library/Python/2.7/lib/site-packages
    '/Users/joan/AutoMask-master'
]
```
Also you need python 3.7 and the path needs to point to the directory `site-packages`.

_Originally posted by @lukas-blecher in https://github.com/lukas-blecher/AutoMask/issues/8#issuecomment-747579133_

**Comment by JBetbe** [comment]
![Captura de Pantalla 2020-12-17 a les 19 22 01](https://user-images.githubusercontent.com/48406431/102527670-ba9fa580-409d-11eb-87bd-86edab2ae616.png)
I followed your instructions but...

**Comment by lukas-blecher** [comment]
seems like you didn't install the required python dependencies in step 4:
`pip install -r requirements.txt`

**Comment by JBetbe** [comment]
> seems like you didn't install the required python dependencies in step 4:
> `pip install -r requirements.txt`

you're probably right. I installed Python 3.7 and now I'm re-installing requirements. I'll say you something.
Thanks for your support.

**Comment by JBetbe** [comment]
I've got this error in terminal: 
![Captura de Pantalla 2020-12-17 a les 19 38 02](https://user-images.githubusercontent.com/48406431/102528880-744b4600-409f-11eb-8151-8f50ba69cdf0.png)

**Comment by lukas-blecher** [comment]
Ok, thank you. I will change the package name
execute `pip insall scikit-image` and you should be done if you already have installed pytorch.

**Comment by JBetbe** [comment]
> Ok, thank you. I will change the package name
> execute `pip insall scikit-image` and you should be done if you already have installed pytorch.

I've done it too but I got the same error as before :( inside Blender

**Comment by lukas-blecher** [comment]
which error?

**Comment by JBetbe** [comment]
> which error?

this 
![Captura de Pantalla 2020-12-17 a les 19 55 16](https://user-images.githubusercontent.com/48406431/102539671-48838c80-40ae-11eb-9176-b37b2ac1c8c2.png)

**Comment by lukas-blecher** [comment]
Then you either did not change the path yet in automask.py or you installed the dependencies in the wrong python. You need the pip for the python 3.7
maybe its called `pip3`

**Comment by JBetbe** [comment]
python --version
Python 3.8.6

paths = [
   '/Users/joan/Library/Python/3.8/lib/python/site-packages'
   '/Users/joan/AutoMask-master'    
]

and ...

![Captura de Pantalla 2020-12-17 a les 21 58 21](https://user-images.githubusercontent.com/48406431/102543095-0b6dc900-40b3-11eb-9f72-1ed5f4e23e00.png)

**Comment by lukas-blecher** [comment]
the python version of blender must be compatible with the extern version i.e. both need to be the same version.
The blender version is 3.7

**Comment by JBetbe** [comment]
> the python version of blender must be compatible with the extern version i.e. both need to be the same version.
> The blender version is 3.7


python --version                                            
Python 3.7.9

and in Blender:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/joan/Library/Application Support/Blender/2.91/scripts/addons/automask.py", line 15, in <module>
    from mask_spline import *
  File "/Users/joan/Library/Application Support/Blender/2.91/scripts/addons/mask_spline.py", line 1, in <module>
    from geomdl import BSpline
ModuleNotFoundError: No module named 'geomdl'

I modified the automask.py too,  with the current site-packages path

**Comment by lukas-blecher** [comment]
Try to uninstall the Addon in blender and reinstall it. The version blender uses might be an cached one.

**Comment by JBetbe** [comment]
I tried two or three times. Remove it and install automask.py again

**Comment by jcnwholland** [comment]
I'm having the same problems, no matter what I try, Is 2.8.0 req? or does it work with other versions?
Why does it create an other location for placing the script? anyone?

Traceback (most recent call last):
  File "C:\blender-2.83.0-windows64\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\automask.py", line 12, in <module>
    from mask_spline import *
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\mask_spline.py", line 1, in <module>
    from geomdl import BSpline
ModuleNotFoundError: No module named 'geomdl'
--



Here is my edited autmask.py 

--
import bpy
from bpy.types import Operator, Panel, PropertyGroup, WindowManager
from bpy.props import PointerProperty, StringProperty, IntProperty, FloatProperty, BoolProperty
import sys
paths = [
    #C:\Program Files\Python37\Lib\site-packages,C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master'
]
for p in paths:
    sys.path.insert(0, p)
from mask_spline import *
from SiamMask import *

bl_info = {
    'blender': (2, 80, 3),
    'name': 'AutoMask',
    'category': 'Motion Tracking',
    'location': 'Masking> Movie Clip Editor > AutoMask',
    'author': 'Lukas Blecher'
}
--
PY-shell:

Installing collected packages: decorator, networkx, imageio, six, cycler, pyparsing, python-dateutil, kiwisolver, matplotlib, scipy, tifffile, PyWavelets, scikit-image
  The scripts imageio_download_bin.exe and imageio_remove_bin.exe are installed in 'c:\program files\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts lsm2bin.exe, tiffcomment.exe and tifffile.exe are installed in 'c:\program files\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script skivi.exe is installed in 'c:\program files\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed PyWavelets-1.1.1 cycler-0.10.0 decorator-4.4.2 imageio-2.9.0 kiwisolver-1.3.1 matplotlib-3.3.3 networkx-2.5 pyparsing-2.4.7 python-dateutil-2.8.1 scikit-image-0.18.0 scipy-1.5.4 six-1.15.0 tifffile-2020.12.8
You are using pip version 10.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
--

C:\Users\Administrator>pip install -r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt
Requirement already satisfied: opencv_python_headless>=4.1.1.26 in c:\program files\python37\lib\site-packages (from -r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 2)) (4.4.0.46)
Requirement already satisfied: imutils>=0.5.3 in c:\program files\python37\lib\site-packages (from -r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 3)) (0.5.3)
Requirement already satisfied: geomdl>=5.2.9 in c:\program files\python37\lib\site-packages (from -r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 4)) (5.3.0)
Requirement already satisfied: torch>=1.3.1 in c:\program files\python37\lib\site-packages (from -r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 5)) (1.7.1+cu110)
Requirement already satisfied: numpy>=1.18.0 in c:\program files\python37\lib\site-packages (from -r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 6)) (1.19.4)
Requirement already satisfied: Pillow>=6.2.1 in c:\program files\python37\lib\site-packages (from -r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 7)) (8.0.1)
Requirement already satisfied: scikit-image in c:\program files\python37\lib\site-packages (from -r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (0.18.0)
Requirement already satisfied: typing-extensions in c:\program files\python37\lib\site-packages (from torch>=1.3.1->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 5)) (3.7.4.3)
Requirement already satisfied: imageio>=2.3.0 in c:\program files\python37\lib\site-packages (from scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (2.9.0)
Requirement already satisfied: scipy>=1.0.1 in c:\program files\python37\lib\site-packages (from scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (1.5.4)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in c:\program files\python37\lib\site-packages (from scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (3.3.3)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\program files\python37\lib\site-packages (from scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (1.1.1)
Requirement already satisfied: networkx>=2.0 in c:\program files\python37\lib\site-packages (from scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (2.5)
Requirement already satisfied: tifffile>=2019.7.26 in c:\program files\python37\lib\site-packages (from scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (2020.12.8)
Requirement already satisfied: python-dateutil>=2.1 in c:\program files\python37\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\program files\python37\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\program files\python37\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\program files\python37\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (0.10.0)
Requirement already satisfied: decorator>=4.3.0 in c:\program files\python37\lib\site-packages (from networkx>=2.0->scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (4.4.2)
Requirement already satisfied: six>=1.5 in c:\program files\python37\lib\site-packages (from python-dateutil>=2.1->matplotlib!=3.0.0,>=2.0.0->scikit-image->-r C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master\requirements.txt (line 8)) (1.15.0)
You are using pip version 10.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by jcnwholland** [comment]
Or am i linking it the wrong way? the path joan is required right?

**Comment by lukas-blecher** [comment]
@jcnwholland try with
```
paths = [
r'C:\Program Files\Python37\Lib\site-packages', r'C:\Users\Administrator\Downloads\AutoMask-master\AutoMask-master'
]
```
I will update the README to make that a bit clearer. you commented the paths out.
I'm checking if blender 2.9 is posing problems now.

**Comment by lukas-blecher** [comment]
Something changed from 2.8 to 2.9 
Right now the addon requires 2.8x.

**Comment by JBetbe** [comment]
Ok. I see, thanks! keep us updated, please!
